# Input desired initial state and goal state. Each '-' represent a row in
# the matrix, DO NOT DELETE the '-'!

a_star:
  heuristic: manhattan # choices: manhattan or misplaced
  init_state:
    - [1, 2, 3]
    - [4, 6, 7]
    - [5, 8, 0]
  goal_state:
    - [1, 2, 3]
    - [4, 5, 6]
    - [7, 8, 0]

# Test examples

# Possible
  # Test 1
  # init_state:
  #   - [1, 2, 3]
  #   - [4, 7, 5]
  #   - [6, 8, 0]
  # goal_state:
  #   - [1, 2, 3]
  #   - [4, 5, 6]
  #   - [7, 8, 0]
  # Test 2
  # init_state:
  #   - [2, 8, 1]
  #   - [3, 4, 6]
  #   - [7, 5, 0]
  # goal_state:
  #   - [3, 2, 1]
  #   - [8, 0, 4]
  #   - [7, 5, 6]
  # Test 3
  # init_state:
  #   - [3, 5, 1]
  #   - [2, 4, 6]
  #   - [7, 8, 0]
  # goal_state:
  #   - [3, 2, 1]
  #   - [8, 0, 4]
  #   - [7, 5, 6]
  # Test 4
  #   init_state:
  #   - [3, 5, 1]
  #   - [2, 4, 6]
  #   - [7, 8, 0]
  # goal_state:
  #   - [5, 6, 0]
  #   - [8, 1, 4]
  #   - [7, 2, 3]

# Impossible
  # init_state:
  #   - [2, 1, 0]
  #   - [5, 4, 3]
  #   - [6, 7, 8]
  # goal_state:
  #   - [0, 8, 7]
  #   - [6, 5, 4]
  #   - [3, 2, 1]