problem:
  region: au # optionsL: us or au
  domain_size: 3 # number of colors to work with
csp:              
  seed: 3
  forward_checking: False # enable forward checking
  propagation: False # enable propagation through singletons 
  heuristics: True  # enable heuristics for unassigned selection and domain selection