region: us # optionsL: us or au
seed: 1
domain_size: 4 # number of colors to work with
forward: False # enable forward checking
propagation: False # enable propagation through singletons 
heuristic: null # options mrv, degree, least, or null (i.e. None)